spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service-route
              uri: http://auth-service:10001
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: patient-service-route
              uri: http://patient-service:5000
              predicates:
                - Path=/api/patients
              filters:
                - SetPath=/patients
                - JwtValidation

            - id: api-docs-patient-route
              uri: http://patient-service:5000
              predicates:
                - Path=/api-docs/patients
              filters:
                - SetPath=/v3/api-docs